spring:
  profile:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
#spring.jpa.show-sql: true

jwt:
  secret: fcdf83ad-7066-4e21-b8cf-f621c480c598
  expiration: 999999
